version: '3.4'

services:

  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD: jduwYykD9NmFAmQf
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"

  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  basketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BASKETAPI_PATH_BASE=/basket/
      - BASKETAPI_IdentityApiExternal=http://localhost:5002
      - BASKETAPI_IdentityApi=http://identityapi
    ports:
      - "80"

  categoriesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CATEGORIESAPI_PATH_BASE=/categories/
      - CATEGORIESAPI_IdentityApiExternal=http://localhost:5002
      - CATEGORIESAPI_IdentityApi=http://identityapi
      - CATEGORIESAPI_ConnectionStrings__CategoriesDb=User ID=postgres;Password=jduwYykD9NmFAmQf;Host=postgres;Port=5432;Database=wizload_categories;
    ports:
      - "80"

  notificationsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NOTIFICATIONSAPI_PATH_BASE=/notifications/
      - NOTIFICATIONSAPI_IdentityApiExternal=http://localhost:5002
      - NOTIFICATIONSAPI_IdentityApi=http://identityapi
    ports:
      - "80"

  productsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PRODUCTSAPI_PATH_BASE=/products/
      - PRODUCTSAPI_IdentityApiExternal=http://localhost:5002
      - PRODUCTSAPI_IdentityApi=http://identityapi
      - PRODUCTSAPI_ConnectionStrings__ProductsDb=User ID=postgres;Password=jduwYykD9NmFAmQf;Host=postgres;Port=5432;Database=wizload_products;
    ports:
      - "80"

  shopmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SHOPMVC_IdentityApiExternal=http://localhost:5002
      - SHOPMVC_IdentityApi=http://identityapi
      - SHOPMVC_CallBackUrl=http://localhost:5000
      - SHOPMVC_CategoriesApi=http://categoriesapi
      - SHOPMVC_ProductsApi=http://productsapi
    ports:
      - "5000:80"