version: '3.4'

services:

  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD: jduwYykD9NmFAmQf
    ports:
      - "5432:5432"

  adminer:
    restart: always
    ports:
      - "8080:8080"

  redis:
    environment:
      - REDIS_PASSWORD=9cRtYehfr2gA52zH
    ports:
      - '6379:6379'

  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"

  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  basketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BASKETAPI_PATH_BASE=/basket/
      - BASKETAPI_IdentityApiExternal=http://localhost:5002
      - BASKETAPI_IdentityApi=http://identityapi
      - BASKETAPI_Redis__Host=redis
      - BASKETAPI_Redis__Port=6379
      - BASKETAPI_Redis__Password=9cRtYehfr2gA52zH
    ports:
      - "80"

  categoriesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CATEGORIESAPI_PATH_BASE=/categories/
      - CATEGORIESAPI_IdentityApiExternal=http://identityapi
      - CATEGORIESAPI_IdentityApi=http://identityapi
      - CATEGORIESAPI_ConnectionStrings__CategoriesDb=User ID=postgres;Password=jduwYykD9NmFAmQf;Host=postgres;Port=5432;Database=wizload_categories;
    ports:
      - "80"

  notificationsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NOTIFICATIONSAPI_PATH_BASE=/notifications/
      - NOTIFICATIONSAPI_IdentityApiExternal=http://localhost:5002
      - NOTIFICATIONSAPI_IdentityApi=http://identityapi
    ports:
      - "80"

  productsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PRODUCTSAPI_PATH_BASE=/products/
      - PRODUCTSAPI_IdentityApiExternal=http://identityapi
      - PRODUCTSAPI_IdentityApi=http://identityapi
      - PRODUCTSAPI_ConnectionStrings__ProductsDb=User ID=postgres;Password=jduwYykD9NmFAmQf;Host=postgres;Port=5432;Database=wizload_products;
    ports:
      - "80"

  imagesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IMAGESAPI_PATH_BASE=/images/
      - IMAGESAPI_IdentityApiExternal=http://identityapi
      - IMAGESAPI_IdentityApi=http://identityapi
      - "IMAGESAPI_ConnectionStrings__AzureBlobStorage=${AzureBlobStorage}"
    ports:
      - "80"

  ordersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ORDERSAPI_PATH_BASE=/orders/
      - ORDERSAPI_IdentityApiExternal=http://identityapi
      - ORDERSAPI_IdentityApi=http://identityapi
      - ORDERSAPI_ConnectionStrings__OrdersDb=User ID=postgres;Password=jduwYykD9NmFAmQf;Host=postgres;Port=5432;Database=wizload_orders;
    ports:
      - "80"

  shopmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SHOPMVC_IdentityApiExternal=http://localhost:5002
      - SHOPMVC_IdentityApi=http://identityapi
      - SHOPMVC_CallBackUrl=http://localhost:5000
      - SHOPMVC_CategoriesApi=http://categoriesapi
      - SHOPMVC_ProductsApi=http://productsapi
      - SHOPMVC_ImagesApi=http://imagesapi
      - SHOPMVC_OrdersApi=http://ordersapi
    ports:
      - "5000:80"