version: '3.4'

services:
  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"

  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  basketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BASKETAPI_PATH_BASE=/basket/
      - BASKETAPI_IdentityApiExternal=http://localhost:5002
      - BASKETAPI_IdentityApi=http://identityapi
    ports:
      - "80"

  categoriesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  notificationsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  shopmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
